import MainLayout from "@/layout/MainLayout"
import {
  Box,
  Button,
  Container,
  Flex,
  HStack,
  Heading,
  Icon,
  Spacer,
  Stack,
  Text,
} from "@chakra-ui/react"
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { CiMenuBurger } from "react-icons/ci"
import { FaArrowLeft } from "react-icons/fa"
import { HiArrowSmallDown } from "react-icons/hi2"
import { IoMenu } from "react-icons/io5"
import { RxHamburgerMenu } from "react-icons/rx"
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout bg={"brand.100"} color={"brand.300"}>
        {/* <HStack h={28} mb={20}>
          <Heading fontSize={"3xl"} fontWeight={"extrabold"}>
            RC
          </Heading>
          <Spacer />
          <Icon as={RxHamburgerMenu} boxSize={"9"} cursor={"pointer"}></Icon>
        </HStack>
        <Flex alignItems={"center"} gap={4} mb={8}>
          <Text display={"inline"} fontSize={"xl"}>
            01//04 -{" "}
            <Text as={"span"} textTransform={"uppercase"}>
              Scroll
            </Text>{" "}
          </Text>
          <Icon
            as={HiArrowSmallDown}
            boxSize={"5"}
            cursor={"pointer"}
            _hover={{
              transition: "all 0.2s ease-out",
              transform: "rotate(180deg)",
            }}
          />
        </Flex>
        <Stack spacing={8}>
          <Flex flexDirection={"column"}>
            <Text
              fontSize={"6xl"}
              textTransform={"uppercase"}
              fontWeight={"black"}
              mx={"auto"}
              display={"inline-block"}
              mb={-5}
            >
              Versatile
            </Text>
            <Text
              fontSize={"6xl"}
              textTransform={"uppercase"}
              fontWeight={"black"}
              mx={"auto"}
              mb={-5}
            >
              Creative
            </Text>
            <Text
              fontSize={"6xl"}
              textTransform={"uppercase"}
              fontWeight={"black"}
              mx={"auto"}
            >
              Visionary
            </Text>
          </Flex>
          <Text textAlign={"center"} mx={"auto"} fontSize={"xl"} mb={16}>
            EXPLORING BOUNDLESS CREATIVITY, I SOLVE PROBLEMS WITH PASSION,
            FUELED BY DESIGN.
          </Text>
          <Button
            border={"3px solid"}
            borderColor={"brand.300"}
            bg={"transparent"}
            rounded={"full"}
            h={32}
            w={32}
            outline={"none"}
            color={"brand.300"}
            mx={"auto"}
          >
            <Icon as={HiArrowSmallDown} boxSize={"10"} cursor={"pointer"} />
          </Button>
        </Stack> */}
      </MainLayout>
    </>
  )
}

// My test text
{
  /* <Text color={"brand.300"}>HELLO THERE! WELCOME MONTSERRAT</Text>
          <Box as={Link} href={"/test"} color={"white"}>
            TEST
          </Box> */
}
